src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    /**
     * @var Collection<int, Session>
     */
    #[ORM\OneToMany(targetEntity: Session::class, mappedBy: 'formation')]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setFormation($this);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getFormation() === $this) {
                $session->setFormation(null);
            }
        }

        return $this;
    }

    public function getNextSession(): ?Session
    {
        $now = new \DateTime();
        foreach ($this->sessions as $session)
        {
            if ($session->getStartDate() > $now)
            {
                return $session;
            }
        }
        return null;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endDate = null;

    /**
     * @var Collection<int, SessionModule>
     */
    #[ORM\OneToMany(targetEntity: SessionModule::class, mappedBy: 'session', cascade: ['remove'], orphanRemoval: true)]
    private Collection $sessionModules;

    /**
     * @var Collection<int, Intern>
     */
    #[ORM\ManyToMany(targetEntity: Intern::class, mappedBy: 'sessions')]
    private Collection $interns;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formation $formation = null;

    public function __construct()
    {
        $this->sessionModules = new ArrayCollection();
        $this->interns = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * @return Collection<int, SessionModule>
     */
    public function getSessionModules(): Collection
    {
        return $this->sessionModules;
    }

    public function addSessionModule(SessionModule $sessionModule): static
    {
        if (!$this->sessionModules->contains($sessionModule)) {
            $this->sessionModules->add($sessionModule);
            $sessionModule->setSession($this);
        }

        return $this;
    }

    public function removeSessionModule(SessionModule $sessionModule): static
    {
        if ($this->sessionModules->removeElement($sessionModule)) {
            // set the owning side to null (unless already changed)
            if ($sessionModule->getSession() === $this) {
                $sessionModule->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Intern>
     */
    public function getInterns(): Collection
    {
        return $this->interns;
    }

    public function addIntern(Intern $intern): static
    {
        if (!$this->interns->contains($intern)) {
            $this->interns->add($intern);
            $intern->addSession($this);
        }

        return $this;
    }

    public function removeIntern(Intern $intern): static
    {
        if ($this->interns->removeElement($intern)) {
            $intern->removeSession($this);
        }

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    public function getTauxRemplissage(): float
    {
        $nbInsctis = $this->interns->count();
        return ($nbInsctis / $this->getCapacity()) * 100;
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Repository\SessionRepository;
use App\Repository\FormationRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FormationController extends AbstractController
{
    #[Route('formations', name: 'list_formation')]
    public function list(FormationRepository $formationRepository): Response
    {
        $formations = $formationRepository->findBy([], ['name' => 'ASC']);

        return $this->render('formation/list.html.twig', [
            'formations' => $formations,
        ]);
    }

    #[Route('formation/{id}', name: 'listById_formation')]
    public function listByIdFormation($id, SessionRepository $sessionRepository, FormationRepository $formationRepository): Response
    {
    

        $formation = $formationRepository->find($id);

        $sessions = $sessionRepository->findBy(['formation' => $formation]);

        return $this->render('formation/listByIdFormation.html.twig', [
            'formation' => $formation,
            'sessions' => $sessions,
        ]);
    }
}

templates/formation/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formations disponibles{% endblock %}

{% block body %}
<div class="tableau">
    <h1 class="forma">Prochaines formations disponibles</h1>
    <table class="table table-striped table-bordered">
        <thead  >
            <tr>
                <th>Nom de la session</th>
                <th>Prochaine session</th>
                <th>Capacité</th>
                <th>Stagiaires inscrits</th>
                <th>Taux de remplissage</th>
            </tr>
        </thead>
        <tbody>
            {% for formation in formations %}
                <tr>
                    <td>
                        <a href="{{path('listById_formation', {id:formation.id})}}">{{ formation.name }}</a>
                    </td>
                    {% set nextSession = formation.getNextSession %}
                    {% if nextSession %}
                        <td>{{ nextSession.startDate|date("d/m/Y") }}</td>
                        <td>{{ nextSession.capacity }}</td>
                        <td>{{ nextSession.interns|length }}</td>
                        <td>{{ nextSession.tauxRemplissage }}%</td>
                    {% else %}
                        <td colspan="5">Pas de session à venir</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/formation/listByIdFormation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sessions pour la formation{% endblock %}

{% block body %}
<h1>Formations disponibles actuellement</h1>
<div class="tableau table-responsive">
    <a href="{{ path('new_session')}}">
        <button type="button">Add Session</button>
    </a>
    
    <table class="table table-striped table-bordered">
        <thead class="table-secondary">
            <tr>
                <th>Nom de la session</th>
                <th>Date début</th>
                <th>Date fin</th>
                <th>Capacité</th>
                <th>Stagiaires inscrits</th>
                <th>Taux de remplissage</th>
                <th>Programme</th>
            </tr>
        </thead>
        <tbody>
            {% for session in sessions %}
                <tr>
                    <td>{{ session.formation.name }}</td>
                    <td>{{ session.startDate|date("d/m/Y") }}</td>
                    <td>{{ session.endDate|date("d/m/Y") }}</td>
                    <td>{{ session.capacity }}</td>
                    <td>{{ session.interns|length }}</td>
                    <td>{{ session.tauxRemplissage }}%</td>
                    <td>
                        <a href="{{ path('detail_session', {id: session.id })}}">
                            <img src="{{ asset('img/Program.png')}}" alt="logo de programme" class="program_logo">
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}